"""empty message

Revision ID: f04b1ea81d4d
Revises: 
Create Date: 2024-11-12 23:03:38.651415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04b1ea81d4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('numeroDepart', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('numeroEmpregado', sa.Integer(), nullable=False),
    sa.Column('dataInicio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('numeroDepart'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('numeroDepart'),
    sa.UniqueConstraint('numeroEmpregado')
    )
    op.create_table('dependente',
    sa.Column('numeroDependente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('sexo', sa.String(length=15), nullable=True),
    sa.Column('dataNasc', sa.DateTime(), nullable=True),
    sa.Column('tipoRelacionamento', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('numeroDependente'),
    sa.UniqueConstraint('numeroDependente')
    )
    op.create_table('empregado',
    sa.Column('nss', sa.Integer(), nullable=False),
    sa.Column('pnome', sa.String(length=50), nullable=False),
    sa.Column('mnome', sa.String(length=50), nullable=False),
    sa.Column('snome', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.String(length=15), nullable=False),
    sa.Column('dataNasc', sa.DateTime(), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.Column('endereco', sa.String(length=50), nullable=True),
    sa.Column('nssSupervisor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nssSupervisor'], ['empregado.nss'], ),
    sa.PrimaryKeyConstraint('nss'),
    sa.UniqueConstraint('mnome'),
    sa.UniqueConstraint('nss'),
    sa.UniqueConstraint('snome')
    )
    op.create_table('localizacao',
    sa.Column('localizacaoKey', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('localizacaoKey'),
    sa.UniqueConstraint('localizacaoKey')
    )
    op.create_table('projeto',
    sa.Column('numero_Projeto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('numero_Projeto'),
    sa.UniqueConstraint('numero_Projeto')
    )
    op.create_table('trabalha-em',
    sa.Column('tbkey', sa.Integer(), nullable=False),
    sa.Column('horas', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tbkey'),
    sa.UniqueConstraint('tbkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabalha-em')
    op.drop_table('projeto')
    op.drop_table('localizacao')
    op.drop_table('empregado')
    op.drop_table('dependente')
    op.drop_table('departamento')
    # ### end Alembic commands ###
